server:
 port: 8080
 servlet:
    context-path: /wakanda-academy/app

spring:
  data:
    mongodb:
      authentication-database: admin
      uri:  ${MONGO_DB_URI}

wakanda:
  jwt:
    chave: 123456
    expiracao: 15