server:
 port: 8080
 servlet:
    context-path: /wakanda-academy/app

spring:
  data:
    mongodb:
      authentication-database: admin
      uri:  mongodb+srv://wakanda:jnjmuc0GxHsPHuoH@wakandacluster.frepd.mongodb.net/wakanda?retryWrites=true&w=majority

wakanda:
  jwt:
    chave: 123456
    expiracao: 15