server:
 port: 8080
 servlet:
    context-path: /wakanda-academy/app

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb://root:root@127.0.0.1:27017/wakanda?authSource=admin}
      auto-index-creation: true

wakanda:
  jwt:
    chave: 123456
    expiracao: 15