server:
 port: 8080
 servlet:
    context-path: /wakanda-academy/app

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb+srv://Gaesilva:Nikita01@cluster0.h5jjr.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      auto-index-creation: true

wakanda:
  jwt:
    chave: 123456
    expiracao: 15